# Generated by Django 5.2.7 on 2025-10-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14)),
                ('is_valid', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Call Log',
                'verbose_name_plural': 'API Call Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='validatorAp_timesta_6d22e7_idx'), models.Index(fields=['user', '-timestamp'], name='validatorAp_user_id_3011a1_idx')],
            },
        ),
    ]
